In [85]:
import numpy as np

# how to create an array


In [86]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [87]:
type(a)

numpy.ndarray

# Basic operations of array

In [88]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [89]:
# creating a 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [90]:
# creating a 3D array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [91]:
print(a2.shape)
print(a3.shape)

(2, 3)
(2, 2, 3)


In [92]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])  #2d array with 3 rows and 3 columns

y = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])     #2d array with 3 rows and 3 columns

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [93]:
print(x+y)
print(x-y)
print(x*y)

[[ 8  4  6]
 [ 6 10  8]
 [10 13 10]]
[[ 6  0  0]
 [-2  0 -4]
 [-4 -3 -8]]
[[ 7  4  9]
 [ 8 25 12]
 [21 40  9]]


In [94]:
print(x@y) #matrix multiplication

[[36 48 60]
 [36 45 54]
 [30 39 48]]


In [95]:
np.dot(x,y)

array([[36, 48, 60],
       [36, 45, 54],
       [30, 39, 48]])

In [96]:
x.prod() #product of all elements in the array

np.int64(12600)

In [97]:
x.mean() #prodouct of all elements in the array 

np.float64(3.3333333333333335)

In [98]:
x.mean(axis=0) #mean of each column

array([4., 4., 2.])

In [99]:
y.mean(axis=1) #mean of each row

array([2., 5., 8.])

In [100]:
print(x.sum()) #sum of all elements in the array 
print(x.var()) #varience of all elements in the array 
print(x.std()) #standard deviation of all elements in the array

30
3.3333333333333335
1.8257418583505538


In [101]:
a = np.array ([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25)) #25th percentile
print(np.percentile(a, 50)) #50th percentile
print(np.percentile(a, 75)) #75th percentile

3.0
5.0
7.0


In [103]:
b = np.array ([[59,29,93,93],
             [84,60,30,66],
             [66,63,38,20],
             [31,32,61,92]])
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [104]:
print('2*8')
print(b.reshape(2,8))

2*8
[[59 29 93 93 84 60 30 66]
 [66 63 38 20 31 32 61 92]]


In [105]:
print('8*2')
print(b.reshape(8,2))

8*2
[[59 29]
 [93 93]
 [84 60]
 [30 66]
 [66 63]
 [38 20]
 [31 32]
 [61 92]]


In [106]:
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [108]:
print(b[0])
print(b[1])

[59 29 93 93]
[84 60 30 66]


In [109]:
print(b[0,0])

59
